BEGIN TRANSACTION;
CREATE TABLE `vendors` (
	`vendor_code`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`address`	TEXT
);
CREATE TABLE `units` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`unit`	TEXT NOT NULL UNIQUE
);
CREATE TABLE "items" (
	`item_code`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`item_description`	TEXT,
	`quantity`	REAL NOT NULL,
	`unit`	INTEGER NOT NULL
);
COMMIT;
